language: node_js
node_js:
  - "11.0"
before_script:
  - npm install -g firebase-tools
stages:
  - test
  - name: deploy-staging
    if: branch = staging
  - name: deploy-production
    if: branch = master
jobs:
  include:
    - stage: deploy-staging
      script:
        - cd web
        - firebase deploy --only hosting:staging
    - stage: deploy-production
      script:
        - cd web
        - firebase deploy --only hosting:production
